// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scStreamGreeter.proto

package top.creambing.grpc.proto;

public final class ScStreamGreeter {
  private ScStreamGreeter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025scStreamGreeter.proto\032\rgreeter.proto2?" +
      "\n\017SCStreamGreeter\022,\n\010SayHello\022\r.HelloReq" +
      "uest\032\013.HelloReply\"\000(\0010\001B\032\n\030top.creambing" +
      ".grpc.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          top.creambing.grpc.proto.GreeterOuterClass.getDescriptor(),
        }, assigner);
    top.creambing.grpc.proto.GreeterOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
