spring:
  application:
    name: grpc-client
  main:
    banner-mode: log
grpc:
  client:
    grpc-server:
      address: static://localhost:9898
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
server:
  port: 10060